### ISSUE TITLE
Porting `so3.clebsch_gordan`  and `so3.spherical_harmonics` to `e3nn/e3nn-jax`

### ISSUE THREAD

**Issue by mitkotak** [atomicarchitects/BasisLib#2]
@atharvchagi This might be a good first issue to get your feet wet. If you look at e3nn/e3nn-jax, there's a lot of complains about not supporting lmax>=10 spherical_harmonics. I think the machinery should help us resolve that issue since we can precompute, store it as .npz and then call it again.

# TODOS

- [ ] Update the test cases here to get a feel for how the API looks
- [ ] Update e3nn/e3nn-jax.spherical_haromonics
- [ ] Similar process for e3nn/e3nn-jax.clebsch_gordan

I know this is pretty vague. If you are interested can provide more details :)

**Comment by atharvchagi** [comment]
Hi Mit. Thanks, I am interested, could you provide more details please?
